### ISSUE TITLE
First lines of apt.dat causes file unreadable by a lib

### ISSUE THREAD

**Issue by ormopl** [X-Plane/xplane_airports#3]
**Test Scope**
First attempt to use this lib in one of my quick tool for XPlane 11 to XPlane 10/9/8 converting. 
When tried to load full, original file from Xplane 11 via this lib, there is an error that file is not recognized

**Reproducing**
1. In Python, try to create new object with object = AptDat("path_to_dat_file")
2. Try to load it and print it.
3. Lenght of file is zero, AptDat is not recognizing orginal apt.dat file from Xplane 1130, 1100, but 1050,, and 0850 neither. 9 was not tested.
4. After removing first two rows (with I on first position) AptDat is loading and recognizing the file as valid

**Expected behavior**
Expectation was to read all of the files without need to change(remove) the first row of each of them. 

**Desktop (please complete the following information):**
- Python 3.9
- APT 1130, 1100, 1050, 0850
- Windows 10

**Additional context**
Great job with this lib. Thanks!

**Comment by s3cur3** [comment]
Can you post your script and the complete output you're seeing?

Which default apt.dat are you trying to load? It could be either:

- `Resources\default scenery\default apt dat\Earth nav data\apt.dat`, or
- `Custom Scenery\Global Airports\Earth nav data\apt.dat`

**Comment by s3cur3** [comment]
Actually, I may have found it. I just pushed 3.2.2... give that a try.

**Comment by ormopl** [comment]
Yeah well thank you very very much for really fast response. I fell asleep... 
Are you going to fix this, or i am supposed to use Py3.2.2 instead? Generally its not a problem for me i think.

**Comment by s3cur3** [comment]
No, no—I think I've fixed it with version 3.2.2 of the library, which I just released last night. If that _doesn't_ solve the problem for you, please post the script you're using (or try the sample script below), along with the complete output you're seeing.

Sample script from the readme, which is working for me on Windows:

    from xplane_airports.AptDat import AptDat, Airport
    from pathlib import Path

    xplane_installation = Path(input("Path to your X-Plane installation: "))
    assert xplane_installation.is_dir(), f"{xplane_installation} does not exist or is not a directory"
    print("Reading 35,000+ airports from disk (this will take awhile)")
    default_xplane_apt_dat = AptDat(xplane_installation / 'Resources/default scenery/default apt dat/Earth nav data/apt.dat')
    print(f"{len(default_xplane_apt_dat)} airports found in your default apt.dat\n")

**Comment by ormopl** [comment]
Okay, so that was misunderstanding. 
Yesterdays morning there was a error, todays everythings work! 
Are you gonna put that on PyPi to be downloaded via pip?

**Comment by s3cur3** [comment]
Excellent! Glad it's working now. Like so many Python problems, it came down to a text encoding issue. 😬

Re: future development, yes, eventually... the library mostly gets upgraded as we need new features for X-Plane internal dev. Is there particular stuff you'd like to see?

**Comment by ormopl** [comment]
Generally my company is running FNTP Simulating Device with SR22 Cabin. Its running Xplane 8.70, there was an plugin for XP11 written to control simulation via PLC and so on... 
We are trying to update XPlane8.7 APT dat on a base of newer Xplane's APT files. Because im python beginner im trying to solve these issues by myself. 
Just before i found your lib, i was trying to parse it by myself - removing all of 1xxx lines, and so on. But Linear Features form XP11 are completley different than in XP. Newest compatible XP version is 1050. 
If i only could, and have skills for python, i would like to contribute on this project, but i think thats is too early yet. 

I will keep you updated with my scripts, if you would like to. 

Best Regards! Thank you for cooperation!

**Comment by s3cur3** [comment]
Ah, gotcha... yeah, for _removing_ newer row codes, you should be able to filter the lines in each `Airport` to only include the stuff present in [the 8.50 spec](http://developer.x-plane.com/wp-content/uploads/2015/11/XP-APT850-Spec.pdf)... but you're right that for stuff that has changed like the linear features, it'll be a pain...

**Comment by ormopl** [comment]
Well thats why i need to use both xp10 and xp11... Xp11 are newer, but i
have to use inearfeatures from xp10, because these works with xp8... It's
complicated.

wt., 27 paź 2020, 15:02 użytkownik Tyler A. Young <notifications@github.com>
napisał:
